pr:
- Dev

pool:
  vmImage: 'windows-2019'

steps:
- task: CopyFiles@2
  displayName: "Obtain Files from GitHub"
  inputs:
    SourceFolder: '.'
    TargetFolder: '$(build.artifactstagingdirectory)/BuildFiles'
- task: PowerShell@2
  displayName: "Import TestHarness Module"
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: Install-Module Microsoft.Online.SharePoint.PowerShell -RequiredVersion "16.0.19515.12000" -Force -SkipPublisherCheck;Install-Module AzureADPreview -RequiredVersion "2.0.2.89" -Force -SkipPublisherCheck; Install-Module MicrosoftTeams -RequiredVersion "1.0.6" -Force -SkipPublisherCheck;Install-Module "SharePointPnPPowerShellOnline" -RequiredVersion "3.21.2005.1" -Force -SkipPublisherCheck;Install-Module "ReverseDSC" -Requiredversion "2.0.0.2" -Force -SkipPublisherCheck;Install-Module "MSCloudLoginAssistant" -Force -RequiredVersion "1.0.16" -SkipPublisherCheck -AllowClobber;Install-Module "Microsoft.PowerApps.Administration.PowerShell" -Force -RequiredVersion "2.0.57" -SkipPublisherCheck;Install-Module ExchangeOnlineManagement -RequiredVersion 0.4578.0 -Force -SkipPublisherCheck;Install-Module Microsoft.Graph.Authentication -RequiredVersion 0.5.1 -Force -SkipPublisherCheck;Install-Module Microsoft.Graph.Identity.ConditionalAccess -RequiredVersion 0.5.1 -Force -SkipPublisherCheck;Install-Module DSCParser -RequiredVersion 1.1.0.3 -Force -SkipPublisherCheck;[System.Environment]::SetEnvironmentVariable('M365DSCTelemetryEnabled', $false, [System.EnvironmentVariableTarget]::Machine);Import-Module '$(build.artifactstagingdirectory)\BuildFiles\Tests\TestHarness.psm1' -Force;$results = Invoke-TestHarness; if ($results.FailedCount -gt 0){throw "Unit Test Failed"}

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Package'
